services:
  python-api:
    build: .
    ports:
      - "5000:5000"  # ホストの5000番をコンテナの5000番に繋ぐ
    environment:
      - PORT=5000
      - GO_CALLBACK_URL=${GO_CALLBACK_URL}
      - PYTHON_API_SECRET=${PYTHON_API_SECRET}
      - CALLBACK_SECRET=${CALLBACK_SECRET}
      - AI_MODE=${AI_MODE}
      - GO_TEST_RESULT_CALLBACK_URL=${GO_TEST_RESULT_CALLBACK_URL}
      - TEST_BATCH_SIZ=${TEST_BATCH_SIZE}
      - TEST_MAX_IMAGES=${TEST_MAX_IMAGES}
    volumes:
      - ./received_images:/app/storage # 今のディレクトリにあるフォルダをマウント

    devices:
      - nvidia.com/gpu=all
